name: payment-ci-github-actions-test
on:
  workflow_dispatch:
  push:
    branches:
      - github-actions-test
    tags:
      - gat_v*

# concurrency:  
#   group: github-actions-test  
#   # cancel-in-progress: true

env:
  IMAGE_NAME: payment
  #TAG: main_${{ github.run_number }}

jobs:
  payment-ci-github-actions-test:
    runs-on: [self-hosted, Linux, X64, orgrunner]
    concurrency: release
    permissions:
      id-token: write
      contents: write
################################## TAGGING ##################################################
    steps:
    - name: Exit if not on main branch
      if: |
        endsWith(github.ref, 'main') == false &&
        endsWith(github.ref, 'uat') == false
      run: exit -1

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        submodules: true

    - name: 'Get tag'
      id: tag
      uses: 'WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950'

    - name: Set correct environment
      run: |
        TAG=${{ steps.tag.outputs.tag }}
        echo "TAG=$TAG" >> "$GITHUB_ENV"

#####################################  CI  #####################################################
    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        endpoint: builders
      
    # login to the ACR
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
            
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}

    #build and push to ACR (method1)  for AKS runner  
    - run: |
           docker build -f node/Dockerfile -t ${{ secrets.DOCKER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
           docker push ${{ secrets.DOCKER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    # to update deployment yaml file with proper tag
    - name: Update values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/gat/deployment.yml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        branch: main
        targetBranch: main

    - run: |
          cat manifests/gat/deployment.yml
