name: payment-cd-main
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["payment-ci-main"]
    # branches: [main]
    types: 
      - completed
env:
  RGNAME: prachi-rg
  AKSNAME: praks

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64, orgrunner]
    
    steps:
  
   # Checkout the branch
    - uses: actions/checkout@v2
      with:
        ref: main
        submodules: true

   # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AKSNAME }}
        resource-group: ${{ env.RGNAME }}

    #install kubectl on container (runner)
    - uses: azure/setup-kubectl@v3
      with:
        version: ' v1.28.2' # default is latest stable
      id: install
    
    # to access ACR from runner
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ secrets.DOCKER_REGISTRY_URL }}
        container-registry-username: ${{ secrets.DOCKER_USERNAME }}
        container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
        secret-name: k8s-secret
        
    ##to deploy on AKS
    - uses: Azure/k8s-deploy@v4
      with:
        action: deploy
        #private-cluster: true
        manifests: |
          manifests/deployment.yml
